### ISSUE TITLE
Get point pair of result

### ISSUE THREAD

**Issue by aister9** [ZJUCADGeoSim/Hausdorff#1]
Hello, I have interest in this project,
To check the result, I want to debug with visualization however this project hasn`t a way of getting the point pair of results in my see.

Are there any other methods to get the point pair of results?

**Comment by Shuenhoy** [comment]
Hi, thanks for your interest in our project.

I haven't touched this code base for quite a while, so I may be wrong.
The result here contains a `max_point`, I think it should be one of the point pair you wanted. Querying its closest point on the other model should give you the other one. You can either use BVH in this codebase or use something like `igl::AABB`.

https://github.com/ZJUCADGeoSim/Hausdorff/blob/114d8c4986fbbccf51c7a7990bfe9f67daa3773b/src/hausdorff/hausdorff.h#L50-L59

**Comment by aister9** [comment]
Thank you, I will check this.

https://github.com/ZJUCADGeoSim/Hausdorff/blob/114d8c4986fbbccf51c7a7990bfe9f67daa3773b/src/app/main.cpp#L228-L236
